site_name: Отчеты по веб-программированию

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Nunito'

nav:
  - Home: index.md
  - Lab №1:
    - Задание 1: lab1/task_1.md
    - Задание 2: lab1/task_2.md
    - Задание 3: lab1/task_3.md
    - Задание 4: lab1/task_4.md
  - Lab №2:
    - Отчет по лабораторной работе 2: lab2/report.md
  - Lab №3:
    - Отчет по лабораторной работе 3: lab3/report.md
    - Долги по литкодам: lab3/leetcode.md
  - Practical work №3:
    - Отчет по практической работе 3: pr3/report.md
  - Lab №4:
    - Отчет по лабораторной работе 4: lab4/report.md

